# THIS IS HEADING 1(H1 TAG)
## HEADING2(H2 TAG)

In [1]:
import numpy as np

In [2]:
d1 = np.array([45,50,47,67,88,99])
d1

array([45, 50, 47, 67, 88, 99])

In [3]:
d1.shape

(6,)

In [4]:
d1.size

6

In [5]:
d1.ndim

1

In [6]:
d1

array([45, 50, 47, 67, 88, 99])

In [7]:
d1[1]

50

In [8]:
d1[0:3]

array([45, 50, 47])

In [10]:
data = np.array(["yamu",123,"cse","a",50.25])
data

array(['yamu', '123', 'cse', 'a', '50.25'], dtype='<U5')

In [13]:
import time

start_time = time.time()
list1 = [ x for x in range(1,100000)]
list2 = [y for y in range(1,100000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()

print("Time Taken by list concept",end_time-start_time)

Time Taken by list concept 0.025010108947753906


In [21]:
import time

start_time = time.time()

ar1 = np.array(list1)
ar2 = np.array(list2)

ar1*ar2
end_time1 = time.time()
print("Time Taken by numpy is",end_time-start_time)


Time Taken by numpy is -995.0417332649231


In [26]:
d2 = np.array([[45,55,72],[22,33,77],[78,90,66]])
d2

array([[45, 55, 72],
       [22, 33, 77],
       [78, 90, 66]])

In [18]:
d2.shape

(3, 3)

In [19]:
d2.size

9

In [20]:
d2.ndim

2

In [22]:
d2[2]

array([78, 90, 66])

In [28]:
d2[0,2]

72

In [27]:
d2[1].max()

77

In [29]:
d2[:,2]

array([72, 77, 66])

In [30]:
d2[:,1].max()

90

In [31]:
d2[:,0].min()

22

In [32]:
d2[0].sum()

172

In [33]:
d2.sum()

538

In [36]:
d2.sum(axis=0)

array([145, 178, 215])

In [38]:
d2.sum(axis=1)

array([172, 132, 234])

In [57]:
d3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
d3[0]

array([1, 2, 3])

In [58]:
d3[0,0]

array([1, 2, 3])

In [60]:
d3[0,0,1]

2

#  arange()

In [59]:
for i in range(1,11):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 

In [61]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [64]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [66]:
print(np.zeros([3,5]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [67]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [68]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
np.tile(7,[5,5])

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [88]:
d21 = np.array([[14,15,16,17],
                [24,56,79,34]])
d21

array([[14, 15, 16, 17],
       [24, 56, 79, 34]])

In [89]:
add_marks = np.tile(5,[2,5])
add_marks

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [82]:
np.random.random(10)

array([0.45343135, 0.75090288, 0.63692056, 0.08251203, 0.00399315,
       0.20864157, 0.2529011 , 0.02007627, 0.88112129, 0.75055456])

In [84]:
np.random.randint(10)

2

In [85]:
np.random.randint(10,20)

11

In [90]:
np.random.randint(10,20,30)

array([15, 16, 17, 13, 12, 10, 16, 11, 17, 15, 10, 12, 11, 17, 17, 16, 13,
       16, 15, 19, 17, 19, 10, 18, 18, 18, 15, 18, 15, 10])

In [91]:
np.random.randint(10,25,[4,6])

array([[17, 22, 20, 11, 19, 14],
       [21, 21, 20, 13, 14, 22],
       [24, 19, 19, 16, 18, 20],
       [21, 11, 13, 14, 12, 24]])

In [92]:
np.random.rand(10)

array([0.65566186, 0.42578205, 0.70720869, 0.24821567, 0.29274751,
       0.19104782, 0.61419974, 0.37582336, 0.33863531, 0.37135754])

In [93]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [94]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])